# Generated by Django 5.0 on 2024-03-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('afisha', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('customer', models.TextField(blank=True, null=True)),
                ('participants', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
