# Generated by Django 5.0 on 2024-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('afisha', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('participants', models.CharField(blank=True, max_length=150, null=True)),
                ('time', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('original_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
