# Generated by Django 5.0 on 2024-03-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema_events',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cinema_events',
            name='poster',
            field=models.TextField(blank=True, null=True),
        ),
    ]
